{"name": "Login with valid credentials -- @1.3 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: MicrosoftEdge=114.0.1823.51)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF7E717B5B2+64226]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E710BB72+770978]\n\t(No symbol) [0x00007FF7E6ECCC3C]\n\t(No symbol) [0x00007FF7E6EA671E]\n\t(No symbol) [0x00007FF7E6F32E8F]\n\t(No symbol) [0x00007FF7E6F4789F]\n\t(No symbol) [0x00007FF7E6F2EDC3]\n\t(No symbol) [0x00007FF7E6F03BDC]\n\t(No symbol) [0x00007FF7E6F02DC6]\n\t(No symbol) [0x00007FF7E6F04354]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7E7358E59+1319081]\n\t(No symbol) [0x00007FF7E6F7BEE8]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E7057AE1+33553]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E704FF1F+1871]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7E7357A73+1313987]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71141A8+20232]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71107C4+5412]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71108BC+5660]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E7104571+740769]\n\tBaseThreadInitThunk [0x00007FF858897614+20]\n\tRtlUserThreadStart [0x00007FF858EA26F1+33]\n\n", "trace": "  File \"C:\\Python\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 12, in step_impl\n    context.home_page.click_on_my_account()\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\HomePage.py\", line 21, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\BasePage.py\", line 11, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\BasePage.py\", line 34, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigated to Login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: MicrosoftEdge=114.0.1823.51)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF7E717B5B2+64226]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E710BB72+770978]\n\t(No symbol) [0x00007FF7E6ECCC3C]\n\t(No symbol) [0x00007FF7E6EA671E]\n\t(No symbol) [0x00007FF7E6F32E8F]\n\t(No symbol) [0x00007FF7E6F4789F]\n\t(No symbol) [0x00007FF7E6F2EDC3]\n\t(No symbol) [0x00007FF7E6F03BDC]\n\t(No symbol) [0x00007FF7E6F02DC6]\n\t(No symbol) [0x00007FF7E6F04354]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7E7358E59+1319081]\n\t(No symbol) [0x00007FF7E6F7BEE8]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E7057AE1+33553]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E704FF1F+1871]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7E7357A73+1313987]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71141A8+20232]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71107C4+5412]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7E71108BC+5660]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7E7104571+740769]\n\tBaseThreadInitThunk [0x00007FF858897614+20]\n\tRtlUserThreadStart [0x00007FF858EA26F1+33]\n\n", "trace": "  File \"C:\\Python\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 12, in step_impl\n    context.home_page.click_on_my_account()\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\HomePage.py\", line 21, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\BasePage.py\", line 11, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n  File \"D:\\Pycharm\\Behave_Python\\features\\pages\\BasePage.py\", line 34, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1687487382189, "stop": 1687487382233}, {"name": "When I enter valid email address as \"amotoorisamplethree@gmail.com\" and valid password as \"secondthree\" into the fields", "status": "skipped", "start": 1687487384355, "stop": 1687487384355}, {"name": "And I click on Login button", "status": "skipped", "start": 1687487384355, "stop": 1687487384355}, {"name": "Then I should get logged in", "status": "skipped", "start": 1687487384355, "stop": 1687487384355}], "parameters": [{"name": "email", "value": "amotoorisamplethree@gmail.com"}, {"name": "password", "value": "secondthree"}], "start": 1687487377822, "stop": 1687487384355, "uuid": "0bbd28e7-19d0-497b-8096-10c18cd57890", "historyId": "b8fe9129b1e642e140c2c9916553779c", "fullName": "Login Functionality: Login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login"}, {"name": "feature", "value": "Login Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}